# Generated by Django 5.2.9 on 2025-12-11 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Campanha')),
                ('descricao', models.TextField(verbose_name='Descrição da Campanha')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Término')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Doador')),
                ('email', models.EmailField(max_length=254, verbose_name='Email do Doador')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CamanhaDoador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camapanha_doador', to='core.campanha', verbose_name='Campanha')),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doadores', to='core.doador', verbose_name='Doador')),
            ],
            options={
                'unique_together': {('campanha', 'doador')},
            },
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Doação')),
                ('data_doacao', models.DateField(verbose_name='Data da Doação')),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doacoes', to='core.camanhadoador', verbose_name='Campanha')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
