# Generated by Django 5.2.9 on 2025-12-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacao',
            name='ano',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano da Doação'),
        ),
        migrations.AddField(
            model_name='doacao',
            name='mes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mês da Doação'),
        ),
    ]
