# Generated by Django 5.2.9 on 2025-12-15 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_congregacao_alter_doacao_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='congregacao',
            options={'verbose_name': 'Congregação', 'verbose_name_plural': 'Congregações'},
        ),
        migrations.AddField(
            model_name='doacao',
            name='prestado_contas',
            field=models.BooleanField(default=False, verbose_name='Prestado Contas'),
        ),
        migrations.AlterField(
            model_name='doador',
            name='congregacao_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doadores', to='core.congregacao', verbose_name='Congregação'),
        ),
    ]
