# Generated by Django 5.2.9 on 2025-12-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_congregacao_options_doacao_prestado_contas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacao',
            name='recebido_por',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Recebido Por'),
        ),
    ]
